### ISSUE TITLE
Adding Icon to Dock or similar won't launch the app with error.

### ISSUE THREAD

**Issue by DarkXero-dev** [frealgagu/archlinux.amarok#4]
For some reason when app is added to Dock or running from recent apps in menu will result in error..

![Error](https://i.imgur.com/U6EXuuH.png)

It's related to the line at the end of `/usr/share/applications/org.kde.amarok.desktop` where it says `DBusActivatable=true`. Removing that line made the shortcut work as expected.

Hope this helps fixing it in future release...

**Comment by frealgagu** [comment]
I've removed that line from .desktop file and it's working now, thanks a lot.

:1st_place_medal:

**Comment by DarkXero-dev** [comment]
@frealgagu 

Thanks.. Glad we could help .. It's part of my package list on my Distro...
